language: python
branches:
  only:
    - main
    - /(\d+\.?)+/
services:
  - docker
script:
  - echo Script
  - export TRAVIS_TAG=0.7
  - git checkout $TRAVIS_TAG
after_success:
  - if [[ $TRAVIS_TAG =~ ^(\d+\.?)+$ ]]; then git push origin gh-pages; else echo Not pushing "$TRAVIS_TAG"; fi
