language: minimal
services:
  - docker
install:
  - pip install pytest
script:
  - travis_fold start "Unit Tests" && travis_fold end "Unit Tests"
  - travis_fold start "Integration Tests" && docker build . -t mock && docker run -d mock && travis_fold end "Integration Tests"
